databases:
  - name: ppurokaka_DB
    databaseName: ppurokaka_db
    user: ppurokaka
    region: singapore

services:
  - type: web
    name: ppurokaka
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ppurokaka_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

